# Generated by Django 2.2.1 on 2020-09-23 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictTable',
            fields=[
                ('district_id', models.AutoField(db_column='district_id', primary_key=True, serialize=False)),
                ('district_name', models.CharField(db_column='district_name', max_length=100)),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'MASTER_DISTRICT',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettingTable',
            fields=[
                ('gs_id', models.AutoField(db_column='gs_id', primary_key=True, serialize=False)),
                ('gs_name', models.CharField(db_column='gs_name', max_length=100)),
                ('gs_value', models.TextField(blank=True, db_column='gs_value')),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'GLOBAL_SETTING',
            },
        ),
        migrations.CreateModel(
            name='StateTable',
            fields=[
                ('state_id', models.AutoField(db_column='state_id', primary_key=True, serialize=False)),
                ('state_name', models.CharField(db_column='state_name', max_length=100)),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'MASTER_STATE',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=500)),
                ('last_name', models.CharField(db_column='last_name', max_length=500)),
                ('email', models.CharField(db_column='email', max_length=500)),
                ('phone', models.CharField(db_column='phone', max_length=100)),
                ('dob', models.DateTimeField(db_column='dob', default=django.utils.timezone.now)),
                ('password', models.CharField(db_column='password', max_length=500)),
                ('user_type', models.CharField(choices=[(1, 'APP_USER'), (2, 'WEB_USER')], db_column='user_type', default=None, help_text="'APP_USER', 'WEB_USER'", max_length=100)),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('comment', models.CharField(db_column='comment', max_length=500)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
