# Generated by Django 2.2.1 on 2020-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='sponsor_id',
            field=models.IntegerField(db_column='sponsor_id', default=0),
            preserve_default=False,
        ),
    ]
