# Generated by Django 2.2.1 on 2020-10-01 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_usertable_sponsor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTable',
            fields=[
                ('wallet_id', models.AutoField(db_column='wallet_id', primary_key=True, serialize=False)),
                ('ov_cash', models.FloatField(db_column='ov_cash', default=0.0)),
                ('ovr_cash', models.FloatField(db_column='ovr_cash', default=0.0)),
                ('total_ov_cash', models.FloatField(db_column='total_ov_cash', default=0.0)),
                ('total_ovr_cash', models.FloatField(db_column='total_ovr_cash', default=0.0)),
                ('achiver_cash_back', models.FloatField(db_column='achiver_cash_back', default=0.0)),
                ('reward_and_prices', models.FloatField(db_column='reward_and_prices', default=0.0)),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('comment', models.CharField(db_column='comment', max_length=500)),
                ('status', models.CharField(db_column='status', max_length=100)),
                ('user', models.ForeignKey(help_text='FK on UserTable', on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='rest_api.UserTable')),
            ],
            options={
                'db_table': 'WALLET',
            },
        ),
    ]
