# Generated by Django 2.2.1 on 2020-10-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_wallettable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='sponsor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.UserTable'),
        ),
    ]
