# Generated by Django 2.2.1 on 2020-10-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20201002_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='sponsor_id',
            new_name='sponsor',
        ),
    ]
