# Generated by Django 2.2.1 on 2020-10-03 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20201002_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialTable',
            fields=[
                ('tutorial_id', models.AutoField(db_column='wallet_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('video_url', models.TextField(db_column='video_url')),
                ('img_url', models.TextField(db_column='img_url')),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('comment', models.CharField(db_column='comment', max_length=500)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'TUTORIAL',
            },
        ),
    ]
