# Generated by Django 3.0.10 on 2020-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_tutorialtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_type',
            field=models.CharField(choices=[(1, 'APP_USER'), (2, 'WEB_USER')], db_column='user_type', default=None, help_text="'APP_USER','WEB_USER'", max_length=100),
        ),
    ]
