# Generated by Django 3.0.10 on 2020-10-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20201006_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettable',
            old_name='user',
            new_name='user_data',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='usertable',
            name='sponsor_id',
            field=models.IntegerField(db_column='sponsor_id', default=0, help_text='user id'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_type',
            field=models.CharField(choices=[(1, 'APP_USER'), (2, 'WEB_USER')], db_column='user_type', default=None, help_text="'APP_USER', 'WEB_USER'", max_length=100),
        ),
    ]
