# Generated by Django 3.0.10 on 2020-10-08 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20201007_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalTable',
            fields=[
                ('ref_id', models.AutoField(db_column='ref_id', primary_key=True, serialize=False)),
                ('ref_name', models.CharField(db_column='ref_name', max_length=500)),
                ('last_name', models.CharField(db_column='last_name', max_length=500)),
                ('email', models.CharField(db_column='email', max_length=500)),
                ('phone', models.CharField(db_column='phone', max_length=100)),
                ('dob', models.DateTimeField(db_column='dob', default=django.utils.timezone.now)),
                ('password', models.CharField(db_column='password', max_length=500)),
                ('user_type', models.CharField(choices=[(1, 'APP_USER'), (2, 'WEB_USER')], db_column='user_type', default=None, help_text="'APP_USER', 'WEB_USER'", max_length=100)),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('comment', models.CharField(db_column='comment', max_length=500)),
                ('status', models.CharField(db_column='status', max_length=100)),
                ('sponsor_id', models.IntegerField(db_column='sponsor_id', default=0, help_text='user id')),
            ],
            options={
                'db_table': 'REF',
            },
        ),
    ]
