# Generated by Django 3.0.10 on 2020-10-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_referaltable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferalTable',
        ),
    ]
